site_name: Humon Research Lab Knowledge Base

theme:
  name: material
  logo: assets/humon_sassy_skeleton_logo.png
  
  markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        
