site_name: Humon Research Lab Knowledge Base
site_url: https://HuMoN-Research-Lab.github.io

theme:
  name: material
#  logo: assets/humon_sassy_skeleton_logo.png
  
  markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

nav:
    - Home: index.md
    - How to update these docs: how-to-update-these-docs.md
